[tool.poetry]
name = "minGPT-jax"
version = "0.1.0"
description = ""
authors = ["bradspade <brad@spade.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jax = "^0.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
